//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOCWelcomeLetterGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludeEmail {
            get {
                return ((bool)(this["IncludeEmail"]));
            }
            set {
                this["IncludeEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenFileAfterGeneration {
            get {
                return ((bool)(this["OpenFileAfterGeneration"]));
            }
            set {
                this["OpenFileAfterGeneration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int DefaultBranchIndex {
            get {
                return ((int)(this["DefaultBranchIndex"]));
            }
            set {
                this["DefaultBranchIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thank you for choosing Bank of China. Please find your account information enclos" +
            "ed in this letter.")]
        public string SimpleLetterGreatingEng {
            get {
                return ((string)(this["SimpleLetterGreatingEng"]));
            }
            set {
                this["SimpleLetterGreatingEng"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("感谢您选择中国银行，在此列出您持有账户的汇入汇款信息，烦请妥善保管。")]
        public string SimpleLetterGreatingChn {
            get {
                return ((string)(this["SimpleLetterGreatingChn"]));
            }
            set {
                this["SimpleLetterGreatingChn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please kindly refer above information when you make an inward transfer.")]
        public string SimpleLetterBodyLine1Eng {
            get {
                return ((string)(this["SimpleLetterBodyLine1Eng"]));
            }
            set {
                this["SimpleLetterBodyLine1Eng"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请您在汇入汇款时参照以上信息进行操作。")]
        public string SimpleLetterBodyLine1Chn {
            get {
                return ((string)(this["SimpleLetterBodyLine1Chn"]));
            }
            set {
                this["SimpleLetterBodyLine1Chn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please also be aware that you can always check your account information through y" +
            "our online/mobile banking.")]
        public string SimpleLetterBodyLine2Eng {
            get {
                return ((string)(this["SimpleLetterBodyLine2Eng"]));
            }
            set {
                this["SimpleLetterBodyLine2Eng"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("同时，请注意您的以上账户信息均可以在您的手机银行与网上银行查询。")]
        public string SimpleLetterBodyLine2Chn {
            get {
                return ((string)(this["SimpleLetterBodyLine2Chn"]));
            }
            set {
                this["SimpleLetterBodyLine2Chn"] = value;
            }
        }
    }
}
